import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch-inspired color system
        'primary-fixed-dim': '#8387ff',
        'tertiary-fixed': '#f8a010',
        'tertiary-dim': '#e79400',
        'error-container': '#a70138',
        'surface-container-highest': '#232429',
        'secondary-fixed-dim': '#58e7ab',
        'surface-container-low': '#1a1b20',
        'primary-dim': '#6063ee',
        'on-surface-variant': '#b4b4b4',
        'outline-variant': '#404040',
        'inverse-primary': '#494bd7',
        'surface-bright': '#2d2e33',
        'inverse-on-surface': '#4f5469',
        'on-primary-fixed': '#000000',
        'primary': '#a3a6ff',
        'background': '#191a1f',
        'surface-container-high': '#232429',
        'surface-container': '#1f2025',
        'tertiary': '#ffb148',
        'surface-dim': '#191a1f',
        'secondary-dim': '#58e7ab',
        'tertiary-container': '#f8a010',
        'outline': '#757575',
        'on-error': '#490013',
        'on-tertiary': '#573500',
        'secondary-container': '#006c49',
        'on-secondary-fixed-variant': '#006544',
        'on-secondary': '#005a3c',
        'surface': '#191a1f',
        'secondary-fixed': '#69f6b8',
        'on-primary-container': '#0a0081',
        'surface-variant': '#232429',
        'inverse-surface': '#faf8ff',
        'secondary': '#69f6b8',
        'surface-container-lowest': '#0f1014',
        'primary-fixed': '#9396ff',
        'on-primary-fixed-variant': '#0e009d',
        'on-primary': '#0f00a4',
        'on-surface': '#ffffff',
        'surface-tint': '#a3a6ff',
        'on-tertiary-container': '#4a2c00',
        'on-secondary-fixed': '#00452d',
        'on-background': '#ffffff',
        'tertiary-fixed-dim': '#e79400',
        'on-error-container': '#ffb2b9',
        'primary-container': '#9396ff',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary-container': '#e1ffec',
        'error-dim': '#d73357',
        'on-tertiary-fixed-variant': '#563400',
        'error': '#ff6e84',
        // Additional Stitch colors
        'wash': '#e5e5e5',
        'transparent': 'transparent',
      },
      fontFamily: {
        headline: ['"Google Sans"', 'Inter', 'sans-serif'],
        body: ['"Google Sans"', 'Inter', 'sans-serif'],
        label: ['"Google Sans"', 'Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['"Google Sans"', 'Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '12px',
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        '2xl': '28px',
        '3xl': '36px',
        full: '9999px',
      },
      backdropBlur: {
        glass: '40px',
      },
      boxShadow: {
        'stitch': '0 8px 32px rgba(0, 0, 0, 0.4)',
        'stitch-lg': '0 12px 48px rgba(0, 0, 0, 0.5)',
        'stitch-xl': '0 20px 64px rgba(0, 0, 0, 0.6)',
      },
    },
  },
  plugins: [],
}
export default config
