import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch Design System - Material Design 3 Colors
        'primary-fixed-dim': '#8387ff',
        'tertiary-fixed': '#f8a010',
        'tertiary-dim': '#e79400',
        'error-container': '#a70138',
        'surface-container-highest': '#1c253e',
        'secondary-fixed-dim': '#58e7ab',
        'surface-container-low': '#0c1326',
        'primary-dim': '#6063ee',
        'on-surface-variant': '#a5aac2',
        'outline-variant': '#41475b',
        'inverse-primary': '#494bd7',
        'surface-bright': '#222b47',
        'inverse-on-surface': '#4f5469',
        'on-primary-fixed': '#000000',
        'primary': '#a3a6ff',
        'background': '#070d1f',
        'surface-container-high': '#171f36',
        'surface-container': '#11192e',
        'tertiary': '#ffb148',
        'surface-dim': '#070d1f',
        'secondary-dim': '#58e7ab',
        'tertiary-container': '#f8a010',
        'outline': '#6f758b',
        'on-error': '#490013',
        'on-tertiary': '#573500',
        'secondary-container': '#006c49',
        'on-secondary-fixed-variant': '#006544',
        'on-secondary': '#005a3c',
        'surface': '#070d1f',
        'secondary-fixed': '#69f6b8',
        'on-primary-container': '#0a0081',
        'surface-variant': '#1c253e',
        'inverse-surface': '#faf8ff',
        'secondary': '#69f6b8',
        'surface-container-lowest': '#000000',
        'primary-fixed': '#9396ff',
        'on-primary-fixed-variant': '#0e009d',
        'on-primary': '#0f00a4',
        'on-surface': '#dfe4fe',
        'surface-tint': '#a3a6ff',
        'on-tertiary-container': '#4a2c00',
        'on-secondary-fixed': '#00452d',
        'on-background': '#dfe4fe',
        'tertiary-fixed-dim': '#e79400',
        'on-error-container': '#ffb2b9',
        'primary-container': '#9396ff',
        'on-tertiary-fixed': '#2a1700',
        'on-secondary-container': '#e1ffec',
        'error-dim': '#d73357',
        'on-tertiary-fixed-variant': '#563400',
        'error': '#ff6e84',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      backdropBlur: {
        glass: '40px',
      },
      boxShadow: {
        'stitch': '0 8px 32px rgba(0, 0, 0, 0.4)',
        'stitch-lg': '0 12px 48px rgba(0, 0, 0, 0.5)',
        'stitch-xl': '0 20px 64px rgba(0, 0, 0, 0.6)',
      },
    },
  },
  plugins: [],
}
export default config
